// <auto-generated />
namespace GestaoDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDescricaoCategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDescricaoCategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "202301261303508_AddDescricaoCategoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
