// <auto-generated />
namespace GestaoDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migrationsdeajustes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrationsdeajustes));
        
        string IMigrationMetadata.Id
        {
            get { return "202309132006127_Migrations de ajustes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
