// <auto-generated />
namespace GestaoDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inserindorelacionamentodedelegaciaserisp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inserindorelacionamentodedelegaciaserisp));
        
        string IMigrationMetadata.Id
        {
            get { return "202306121438347_inserindo relacionamento de delegacias e risp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
