// <auto-generated />
namespace GestaoDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addlatitudeelongitutde : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlatitudeelongitutde));
        
        string IMigrationMetadata.Id
        {
            get { return "202305240141560_add latitude e longitutde"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
